name: go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: '1.20'
    - name: Build and integration test
      run: |
        go build -cover -v
        mkdir -p coverage/integration
        GOCOVERDIR=$(pwd)/coverage/integration go test ./... -v -count=1
    - name: Rebuild and unit test
      run: |
        go build -v
        go test ./... -count=1 -coverprofile=coverage/unit-coverage.txt
    - name: Process coverage
      run: |
        go tool covdata textfmt -i=coverage/integration -o coverage/integration-coverage.txt
        cp coverage/integration-coverage.txt coverage/coverage.txt
        tail -n +2 coverage/unit-coverage.txt >> coverage/coverage.txt
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: ./coverage/coverage.txt
